### ISSUE TITLE
Wrong result for Kabsch RMSD

### ISSUE THREAD

**Issue by cossio** [hng/BiomolecularStructures.jl#19] opened 2016-04-23 16:29 UTC
Try this:

P = [-1. 0. 0.; 0. 2. 0.; 0. 1. 0.; 0. 1. 1]
Q = [0. -1. -1.; 0. -1. 0; 0. 0. 0.; -1. 0. 0.]

BiomolecularStructures.Kabsch.kabsch_rmsd(P,Q)

It returns

1.058767176431898

But the correct least RMSD is

0.695

**Comment by diegozea** [comment] 2016-04-25 00:44
I'm getting `0.695` using R's [Bio3D](http://thegrantlab.org/bio3d/html/rmsd.html)

```R
library(bio3d)
P <- matrix(c(-1., 0., 0., 0., 2., 0., 0., 1., 0., 0., 1., 1), ncol=3, byrow=TRUE)
Q <- matrix(c(0., -1., -1., 0., -1., 0., 0., 0., 0., -1., 0., 0.), ncol=3, byrow=TRUE)
p <- c(t(P))
q <- c(t(Q))
rmsd(p, q, fit=TRUE)
```

**Comment by diegozea** [comment] 2016-04-25 00:57
@cossio Do you know what the problem is? [The code is well commented here](https://github.com/hng/BiomolecularStructures.jl/blob/master/src/KABSCH/kabsch.jl)

**Comment by cossio** [comment] 2016-04-25 12:01
@diegozea You're right. I was computing that result without checking for reflections. The correct RMSD after superposition is 0.695.

**Comment by cossio** [comment] 2016-04-25 12:03
@diegozea I'm not sure what's wrong. But I did write my own version of the Kabsch optimal rotation matrix:

```
function kabsch!(rotatedX::Matrix{Float64}, X::Matrix{Float64}, Y::Matrix{Float64})
    @assert size(rotatedX) == size(X) == size(Y)
    A::Matrix{Float64} = X' * Y
    χ = eye(A)
    χ[end,end] = sign(det(A))
    u::Matrix{Float64}, σ::Vector{Float64}, v::Matrix{Float64} = svd(A)
    A_mul_B!(rotatedX, X, u * χ * v')
end
```

If the matrices have been translated previously, this computes the correct rotation matrix. Then RMSD(rotatedX, Y) computes the right least RMSD.

**Comment by diegozea** [comment] 2016-04-25 14:49
I don't know linear algebra to understand it, but sounds fine. I have been using BiomolecularStructures, together with MIToS, to superimpose structures my structures. @cossio Would you mind sending a pull request with your code into the [MIToS' PDB module](https://github.com/diegozea/MIToS.jl/tree/master/src/PDB)? I would like to have PDB superimposition in MIToS. Thanks!

**Comment by gp0** [comment] 2016-04-26 06:34
Hi,
i'm going to look into this later today.

**Comment by gp0** [comment] 2016-04-26 07:27
What happens if you run?

P = [-1. 0. 0.; 0. 2. 0.; 0. 1. 0.; 0. 1. 1]
Q = [0. -1. -1.; 0. -1. 0; 0. 0. 0.; -1. 0. 0.]

BiomolecularStructures.Kabsch.rmsd(P,Q)

Maybe it's just a mix up with the functions. kabsch_rmsd is just a wrapper for rmsd(P,kabsch(Q))

I can't check it myself right now.

**Comment by gp0** [comment] 2016-04-26 10:47
Nevermind, it's a bug.

**Comment by diegozea** [comment] 2016-04-26 12:46
@gp0 Can the code proposed by @cossio solve it in the meanwhile?

**Comment by gp0** [comment] 2016-04-26 12:54
Probably, i'm installing the bio3d R package right now so i can generate some test cases.

**Comment by diegozea** [comment] 2016-04-26 13:03
That's great. I was trying to compare both functions, but It was hard to me.

In cossio's code It's: `*(reference', coords)` =
```julia
		# Compute covariance matrix A
		A::Array{Float64,2} = *(coords', reference)	
```

In cossio's code It's `sing(det(A))`
```julia
		# check for reflection
		f::Int64 = sign(det(vt) * det(u))
```
In cossio's code It's `coords * (u * m * vt')`
```julia
		# Calculate the optimal rotation matrix
		rotation::Array{Float64,2} = *(m,*(vt, u'))

		rotation = rotation' # cossio's code doesn't need it
```

**Comment by cossio** [comment] 2016-04-27 18:11
@diegozea I created the pull request into MIToS. (I'm new to Github, let me know if it's alright)

**Comment by diegozea** [comment] 2016-04-27 18:19
Many thanks @cossio ! That was really helpful :D

**Comment by gp0** [comment] 2016-04-27 22:47
@cossio Another pull request here is _obviously_ appreciated ;) Thanks a lot anyway, that should help a lot tracking down what went wrong.

**Comment by diegozea** [comment] 2016-04-27 23:49
I have had problems with the following lines trying to change the BiomolecularStructures' `kabsch` function following the @cossio 's function:

```julia
		rotation = rotation'

		# calculate the transformation
		transformation::Array{Float64,2} = broadcast(-, centroid_q, *(centroid_p, rotation))

		# calculate the optimally rotated matrix and then actually transform it
		superimposed::Array{Float64,2} = broadcast(+, transformation, *(original_coords, rotation))
```

@gp0 What are the differences between the @cossio 's `rotatedX` and that last `superimposed` ? Are that lines needed?

**Comment by gp0** [comment] 2016-04-28 00:31
Will have an answer for you tomorrow, it's 2:30 am here in Germany ;)

**Comment by diegozea** [comment] 2016-05-02 19:45
@gp0 There is any hint about the `kabsch` bug?

**Comment by gp0** [comment] 2016-05-02 23:50
Sorry this took so long, fixed it now and calculates the same (correct) values as cossios solution and bio3d. It boiled down to a matrix centering issue (one wasn't centered correctly). 

Still need to make sure the function parameter order is correct (especially regarding the docs).

**Comment by gp0** [comment] 2016-05-02 23:56
In hindsight, this issue might be connected to #15

**Comment by cossio** [comment] 2016-05-03 14:29
@gp0  Great! A pull request with my code is no longer needed then.

**Comment by gp0** [comment] 2016-05-03 14:55
No, not needed. Hope you didn't already start on it.

**Comment by diegozea** [comment] 2016-05-03 17:54
Great, thanks @gp0 ! Could you push a new (fixed) version into METADATA ?

**Comment by gp0** [comment] 2016-05-04 00:25
Pull request for METADATA is in, closing this issue. Hope this is it :smile: .

**Closed by gp0** 2016-05-04 00:25 UTC
Labels: bug

**Comment by diegozea** [comment] 2016-05-04 04:54
Thanks @gp0 ! :D

**Comment by diegozea** [comment] 2016-05-05 20:35
@gp0 [This BiomolecularStructures' test](https://github.com/hng/BiomolecularStructures.jl/blob/master/test/kabsch.jl#L35) is still wrong, look here: https://github.com/diegozea/MIToS.jl/blob/master/test/kabsch.jl#L58

**Comment by gp0** [comment] 2016-05-06 10:08
You are right, i missed that. Thanks.

**Comment by diegozea** [comment] 2016-06-18 20:25
Is It solved? Otherwise It should be warning again...

**Comment by gp0** [comment] 2016-06-22 13:50
It is indeed solved, but that one test is wonky. I will fix the test this evening.

**Comment by gp0** [comment] 2016-07-05 22:28
Two things:

- I misunderstood you / didn't read your comment well enough, thought it concerned a test in BiomolecularStructures.jl and because of this it took so long ("oh just a wrong value in my tests, huh, tests run fine though") to get back to it.
- Second: The kabsch implementation or more specifically the function in this package doesn't return the _rotation_ matrix, instead it rotates it and then returns it.

If you change your test to

```
'rotationmatrix = kabsch(P, Q)
@test_approx_eq rmsd(P, rotationmatrix) 0.0030426652601371583

```
it's going to pass.
